### ISSUE TITLE
Using as a power meter

### ISSUE THREAD

**Issue by paultanner** [twonk/MyEnergi-App-Api#19]
I am already using this API to boost the tank in certain circumstances.
I was about to get an M-BUS power meter to log the total energy going into the tank via the immersion.  Then I thought:  eddi should know that (at least instantaneously). Looking at the README I do not see an appropriate data output(s) via this API.  Does anyone know if this is possible?

**Comment by twonk** [comment]
I think you want the cgi-jday or cgi-jdayhour calls - then take a look at the h1d property.  I think this is the total diverted amount in Joules over the minute (jday) or hour (jdayhour), so you’d probably want to convert it to Watts or kWh by dividing by the appropriate divisor.

**Comment by twonk** [comment]
Another way would be to repeatedly query the jstatus api, and save the div property then integrate it for the daily total.  https://myenergi.info/viewtopic.php?p=2668#p2668

**Comment by paultanner** [comment]
Thanks for that.  I understand that would give me diverted solar energy.  I want to know *all* energy used by the immersion.  Sorry that my question was too vague.

**Comment by twonk** [comment]
Ah!  Interesting, not considered that, and now some of the properties start to make sense….  Perhaps h1d is heater 1 diversion. And h1b is heater 1 boost -  the total of those should give you all of the energy going to heater 1.  Just conjecture at this point in time.

**Comment by paultanner** [comment]
thx @twonk.  I'll try that.  I have a plugin power meter (no api) to compare the results to.

**Comment by paultanner** [comment]
Reporting back on my first experiment I get 
      imp: 5650800,
      exp: 100680,
      gep: 1281960,
      gen: 9240,
for most hours using jdayhour
Can't say I understand what these are.
As mentioned above I'd like to know how much energy went into the tank.
Any further suggestions?

**Comment by ashleypittman** [comment]
Hi.  I use the API to run a power meter and a bunch of other things, I've not updated it for the Eddi but my code for doing this on the Zappi is at https://github.com/ashleypittman/mec/blob/master/get_zappi_history.py

I do have an Eddi however so I could update that script for the Eddi in the next few days if you're interested.

**Comment by paultanner** [comment]
Thx Ashley.
Your list of fieldnames is very helpful.
All I need to know is which to accumulate to produce the energy imported from the grid and the energy diverted from PV.  I intended to call it once per day.

**Comment by paultanner** [comment]
OK. I tracked all four and concluded that I just need "imp" (boosting from grid) and "gep" (generation from PV). We hardly ever export as we have a battery. "gen" remains a mystery to me - not a problem.

**Comment by ashleypittman** [comment]
> OK. I tracked all four and concluded that I just need "imp" (boosting from grid) and "gep" (generation from PV). We hardly ever export as we have a battery. "gen" remains a mystery to me - not a problem.

"gep" is "Generation Positive", "gen" is "Generation Negative", that is to say power going to your inverter.  Took me a while to work that out though.

It possibly makes sense for DC connected battery systems but for many installations it's completely meaningless.
