### ISSUE TITLE
Exciting

### ISSUE THREAD

**Issue by HeraldCoupe** [twonk/MyEnergi-App-Api#2]
I have an Eddi and a hub is on order. This is very exciting as I want to be able to harvest the Eddi's data into Homeseer.
Do you know if I will be able to determine when Eddi has finished diverting to my immersion heater?

**Comment by twonk** [comment]
yes, you can get that from the "sta" property.   

- 1     Eddi is paused waiting for surplus

- 3     Eddi is heating / diverting - you should see a "div" property showing the watts

- 5     Eddi has stopped / tank is at temperature

Hope that helps

**Comment by HeraldCoupe** [comment]
That’s exactly what I need, thank you. My hub is due to arrive today so I will get to play with it soon.

**Comment by HeraldCoupe** [comment]
Thanks for this, I've got my hub up and running and I can now get the data I need.

**Comment by twonk** [comment]
Yay!  Glad you're up and running!

**Comment by StoricU** [comment]
> Thanks for this, I've got my hub up and running and I can now get the data I need.

sorry to bring up this old thread, but have just ordered myself a Zappi charger and looking for a way to get it incorporated into homeseer.
Could I ask for some assistance regarding how you did it? :)
