### ISSUE TITLE
Endpoint changed?

### ISSUE THREAD

**Issue by thosirl** [twonk/MyEnergi-App-Api#4]
Hi all,
It looks like MyEnerrgi have changed the endpoint?

The docs pointed to https://myenergi.net/cgi-jstatus-E, however while that endpoint is still responding it seems to be delivering stale data (27th August for me)

From a quick poke with the updated app, it's now pointing to s0.myenergi.net
https://s0.myenergi.net/cgi-jstatus-E

Tom

**Comment by twonk** [comment]
Yes, my energi started to assign hubs to different servers.   Have updated the readme to reflect the change.
