### ISSUE TITLE
Server address

### ISSUE THREAD

**Issue by OOHehir** [twonk/MyEnergi-App-Api#5]
Hello,

Many thanks for all your work.

I've yet to confirm it but I suspect the server address (i.e https://sX.myenergi.net/) used to access ones account is related to the last digit of the Hub serial number. So if last digital is 9 the address becomes:

https://s9.myenergi.net/

Hope this is of help!

I've come up with a simple Python script & hope to build on it:

https://github.com/leo389/myenergi_scripts

**Comment by mzealey** [comment]
Yes this fixes it for me - https://myenergi does not work any more.

**Comment by twonk** [comment]
Apologies for the late response, I've not been getting notifications from github.  I've merged @mzealey's changes in.  Many thanks.
